### ISSUE TITLE
switched function parameters

### ISSUE THREAD

**Issue by mefsantos** [franziskuskiefer/hpke-rs#14]
in file dh_kem.rs, line 137 on function `encaps` I believe `self.derive_key_pair` is receiving the parameters in the wrong order.
Specifically: 
```
(l.137) let (pk_e, sk_e) = self.derive_key_pair(&get_random_vec(self.get_secret_len()), suite_id);
```
function signature:
```
(l. 101) fn derive_key_pair(&self, suite_id: &[u8], ikm: &[u8]) -> (PublicKey, PrivateKey)
```
KemTrait's function signature (key.rs): 
 ```
(l. 79) fn derive_key_pair(&self, suite_id: &[u8], ikm: &[u8]) -> (PublicKey, PrivateKey);
```

**Comment by franziskuskiefer** [comment]
Hm, I see something is odd here but this should be part of the test vectors. So either something else is wrong as well, the test vectors need something to cover this, or there is something wrong with the (processing) of the test vectors.

**Comment by franziskuskiefer** [comment]
> Hm, I see something is odd here but this should be part of the test vectors. So either something else is wrong as well, the test vectors need something to cover this, or there is something wrong with the (processing) of the test vectors.

I never got around to implement the injection of the `ikm` from the test vectors. That's why this wasn't tested. It is fixed now.
Thanks again for reporting @mefsantos !
