### ISSUE TITLE
Bad comparison cause Kem Error.cryptoError for P256

### ISSUE THREAD

**Issue by mefsantos** [franziskuskiefer/hpke-rs#15]
File: **dh_kem.rs** 
lines: 35~37
Code:
```c
if dh.len() <= 32 {
    return Err(Error::CryptoError);
}
```

from [Section 4. DH-Based KEM](https://tools.ietf.org/html/draft-irtf-cfrg-hpke-08#section-4.1): P256 dh secret is 32 bytes long.

**Comment by franziskuskiefer** [comment]
If true, this again should fail somewhere.

**Comment by mefsantos** [comment]
Similarly to issue #14 I believe they are not covered by any of the unit tests, since the unit tests only cover KDF and AEAD, not the KEM's key pair generation and encapsulation

**Comment by franziskuskiefer** [comment]
Ok, so this is actually fine. The result of the DH call here is 64 bytes for P256 (X and Y). But we only care about the X coordinate with 32 bytes. The check here is only a sanity check to make sure that copying 32 bytes in the next line works and doesn't panic.

**Comment by mefsantos** [comment]
I guess the lack of documentation of ever crypt might mislead me, and since I am not implementing in RUST, I cannot test this easily. 
However, it is also somewhat confusing that `ecdh_derive`derives a valid P256 point with x and y coordinates, when in fact the purpose of the DH is to generate a symmetric key, which for P256 should be 32 bytes long.

**Comment by franziskuskiefer** [comment]
The purpose of DH is *not* to derive a symmetric key. It generates a common point on the curve that can be used to derive a symmetric key.

**Comment by mefsantos** [comment]
I guess I was oversimplifying the process and probably misinterpreted the output of my crypto package. It probably already outputs the content to be used for the sym. key derivation. thanks for the clarification.
