### ISSUE TITLE
Typo in test_hpke_kat.rs

### ISSUE THREAD

**Issue by mefsantos** [franziskuskiefer/hpke-rs#20]
typo in test vector struct: "HpkeTestVecor"

**Comment by mefsantos** [comment]
Also, a half off-topic question: any particular reason for (hike) mode to be deserialised as u16 when it is defined as u8 in lib.rs?

**Comment by franziskuskiefer** [comment]
Thanks for taking a look and filing the issue. I'll fix both on a branch I'm working on right now. This should get into main soon (I'll update the issue when it does).
The `mode` is probably a copy paste issue because the other "modes" for KEM, KDF, and AEAD are u16.

**Comment by franziskuskiefer** [comment]
fixed in #22
