### ISSUE TITLE
use x25519-dalek instead of -ng version?

### ISSUE THREAD

**Issue by japaric** [franziskuskiefer/hpke-rs#54]
the latest version of x25519-dalek-ng (v1.1.1) does not compile to a no-std target like `thumbv7em-none-eabihf` because it doesn't [disable the default features of its `rand` dependency](https://github.com/rmw-lib/x25519-dalek-ng/blob/d9b195bb4b0d1c4813f6aa92a8126ed84d55ba02/Cargo.toml#L42) and that brings in a dependency on libstd due to its opt-out "std" feature. I can certainly send a fix for that but given that the repository / crate has not been updated / released since early 2021, it's possible that the fix never makes it into a release.

would it be possible to use `x25519-dalek` instead of the -ng one? the former has proper no-std support and seems to be more actively maintained.

**Comment by franziskuskiefer** [comment]
I'd be fine switching to the `-ng` create.

On that crypto provider in general: This crypto provider is really here for convenience but I don't use it too much myself. I know these crates are popular, but I generally recommend using other crypto libraries that don't lead to a dependency hell like this. The everest provider is not maintained anymore and I'll remove it. But I'll add a [libcrux](https://github.com/cryspen/libcrux/) one soon.
