### ISSUE TITLE
please make new crates.io releases

### ISSUE THREAD

**Issue by japaric** [franziskuskiefer/hpke-rs#60]
thanks for getting all those no-std-support PRs merged so quickly! could I further trouble you by asking for new releases of the `hpke-rs`, `hpke-rs-crypto` and `hpke-rs-rust-crypto` crates on crates.io?

**Comment by franziskuskiefer** [comment]
I'll do that. It might take a couple days before I get to it though because I want to make sure everything works in OpenMLS as expected before doing the release.

**Comment by franziskuskiefer** [comment]
Done https://crates.io/crates/hpke-rs
